// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwzzqmnxvsmqhgzxozdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3enpxbW54dnNtcWhnenhvemRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDA2MTUsImV4cCI6MjA3MjI3NjYxNX0.8zOj7siucFn5qtx2no5im9gE0Qk6g6x89aTUC_uK3yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});